### PR TITLE
Fix #253 - Better honor --zoom option.

### LINKED ISSUE #253: Default zoom level only applied when zooming in/out
### Description

It seems that, whatever the default zoom level given in the command line, it only gets applied when I open the application and zoom in/out. If I just open it, the zoom defaults to 1.0, and not to the value I defined.
### Steps to Reproduce Issue

Running, for example, the command:

`nativefier --zoom 1.5 <application-website>`

and running the application.
### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.0.1`
- Version of Node.js (run `$ node --version`): `v4.5.0`
- OS: `Windows 10`
- Architecture `x64`

Thank you!

### PR DESCRIPTION
**Pull request by ronjouch**
* When zooming in/out, start from the options zoom, not 1 (don't jump)
* Add 'Zoom Reset' feature bound to Ctrl+0, with indicative label for non-100% zoom value

### CODE REVIEW

File: app/src/components/menu/menu.js [hunk 1]
```diff
@@ -5,16 +5,21 @@ import {Menu, shell, clipboard} from 'electron';
...
  * @param disableDevTools
  */
-function createMenu({nativefierVersion, appQuit, zoomIn, zoomOut, goBack, goForward, getCurrentUrl, clearAppData, disableDevTools}) {
+function createMenu({nativefierVersion, appQuit, zoomIn, zoomOut, zoomReset, zoomBuildTimeValue, goBack, goForward, getCurrentUrl, clearAppData, disableDevTools}) {
     if (Menu.getApplicationMenu()) {
         return;
     }
+    const zoomResetLabel = (zoomBuildTimeValue === 1.0) ?
+      'Zoom Reset' :
+      'Zoom Reset (to ' + zoomBuildTimeValue * 100 + '%, set at build time)';
```
Comment (jiahaog) [inline app/src/components/menu/menu.js]: Can use ES6 string interpolation here to avoid the string concatenation here

File: app/src/components/menu/menu.js [hunk 2]
```diff
@@ -5,16 +5,21 @@ import {Menu, shell, clipboard} from 'electron';
...
  * @param clearAppData
  * @param disableDevTools
  */
-function createMenu({nativefierVersion, appQuit, zoomIn, zoomOut, goBack, goForward, getCurrentUrl, clearAppData, disableDevTools}) {
+function createMenu({nativefierVersion, appQuit, zoomIn, zoomOut, zoomReset, zoomBuildTimeValue, goBack, goForward, getCurrentUrl, clearAppData, disableDevTools}) {
     if (Menu.getApplicationMenu()) {
         return;
     }
+    const zoomResetLabel = (zoomBuildTimeValue === 1.0) ?
+      'Zoom Reset' :
```
Comment (jiahaog) [inline app/src/components/menu/menu.js]: Is it just me, or does `Reset Zoom` sounds a little better haha

File: app/src/components/menu/menu.js (hunk 1 above)
Comment (ronjouch) [inline app/src/components/menu/menu.js]: @jiahaog will do, forgot we had that in this project 👍

File: app/src/components/menu/menu.js (hunk 2 above)
Comment (ronjouch) [inline app/src/components/menu/menu.js]: @jiahaog I put it this way to have "Zoom things" (In, Out, Reset) visually together, but after all they're already together given the menu position and grouping. Will change.

**Comment by ronjouch** [comment]
Addressed @jiahaog's feedback and pushed updated patch. Ready to merge.
