### PR TITLE
Fix weirdly platform-dependent folder naming logic (PR #850, fix #708)

### LINKED ISSUE #708: Folder naming logic is weirdly dependent on platform
### Description
I'm seeing different behaviour of the folder name depending on whether it's being built for Windows or Linux when using spaces or mixed case.

For example, if I use "--name retrotracks" I get:
```
retrotracks-win32-x64
retrotracks-linux-x64
```

Which is fine. But if I try "--name RetroTracks" I get:
```
RetroTracks-win32-x64
retro-tracks-linux-x64
```

So the output for the Windows platform is correct, but it's wrong for Linux. I'm not even sure how it's deciding to split the two words there. The title tag of the live site is "RetroTracks" and the name I've just given it is identical. So it's rather cryptic how/why it's deciding to add a split in the middle, as well as ignoring the casing. The only reference to the name with a space in is JSON on the site where it's listed as the alternateName (the "name" field is correct, so even if it is using the JSON, it should be using name rather than alternateName).

The second issue is the Windows name, in that win32-x64 doesn't make any sense. It's either win32 or win64, it can't be a 64bit Win32 program ;)

### Details
- Are you nativefying a *public* website? Yes
- Full nativefier command used to build your app: `nativefier --platform windows (or linux) --arch x64 --name RetroTracks --width 1100 --height 960 --honest --ignore-gpu-blacklist --disable-context-menu --disable-dev-tools --single-instance --tray retro.sx RetroTracks-Electron`
- Version of Nativefier: `v7.6.8`
- Version of node.js: `v11.1.0`
- OS: `Arch Linux`

### PR DESCRIPTION
**Pull request by siddharths2710**
For issue #708 

- Changed Kebab casing to removal of space in string for the specific case of Linux platform

- For the issue specifying the directory name as `win32-x64`, I'm not sure if we can edit the platform name directly, since it is the convention followed by electron in its naming.

- Corresponding test also edited as well.

### CODE REVIEW

File: src/utils/sanitizeFilename.js [hunk 1]
```diff
@@ -11,7 +10,7 @@ export default function(platform, str) {
 
   // spaces will cause problems with Ubuntu when pinned to the dock
   if (platform === 'linux') {
-    return _.kebabCase(result);
+    return result.replace(' ', '');
```
Comment (ronjouch) [inline src/utils/sanitizeFilename.js]: This will only replace the first occurence of a space, not all.

Comment (siddharths2710) [reply src/utils/sanitizeFilename.js]: @ronjouch Please check the regex in the new commit to perform the same.

**Comment by ronjouch** [comment]
@siddharths2710 merged. Thanks!
