### PR TITLE
Change logging method to loglevel

### LINKED ISSUE #480: Move all console.*() to loglevel.*() calls, eslint-fail on console.*(), and add more verbose logging
Would help troubleshoot issues like https://github.com/jiahaog/nativefier/issues/479 .

### PR DESCRIPTION
**Pull request by mdh34**
Fixes #480

### CODE REVIEW

File: app/src/helpers/helpers.js [hunk 1]
```diff
@@ -52,7 +53,7 @@ function debugLog(browserWindow, message) {
     browserWindow.webContents.send('debug', message);
   }, 3000);
   // eslint-disable-next-line no-console
```
Comment (ronjouch) [inline app/src/helpers/helpers.js]: Please remove now-unnecessary eslint-disable

**Comment by ronjouch** [comment]
@mdh34 cool, thanks! Merging.
