### PR TITLE
Fix icon path error when passing asar (--conceal) flag (fix #975)

### LINKED ISSUE #975: Receive icon path error (ERRNO -4058) only when executing with --conceal parameter
Greetings,

First and foremost, thank you for this amazing creation!
I would like to bring this to your attention and seek help to overcome this issue.

When running nativefier with the --conceal parameter, I get the following error in the console:
```
Copying icon icon.ico to CompanyName\test-win32-x64\resources\app\icon.ico
Error during build. Run with --verbose for details. [
  [Error: ENOENT: no such file or directory, open 'C:\Users\Sabz\CompanyName\test-win32-x64\resources\app\icon.ico'] {
    errno: -4058,
    code: 'ENOENT',
    syscall: 'open',
    path: 'C:\\Users\\Sabz\\CompanyName\\test-win32-x64\\resources\\app\\icon.ico'
  }
]
```
This does not happen without the conceal parameter.
I think this error is caused by the following but I am not sure how to fix it:

- Only with the conceal mode, the path resources/app no longer exists. Because it's concealed to resources/app.asar thus the script is failing to copy/retrieve to a path that does not exist.

Thank you again, and I hope that you and your families are safe and well during this pandemic.
Cordially, Sabz

### PR DESCRIPTION
**Pull request by sorhtyre**
By moving icon copy before packaging by `electron-packager` occurs.

### CODE REVIEW

File: src/build/buildNativefierApp.ts [hunk 1]
```diff
@@ -1,7 +1,9 @@
 import * as path from 'path';
 
+import * as asar from 'asar';
 import * as electronGet from '@electron/get';
 import * as electronPackager from 'electron-packager';
+import * as fs from 'fs-extra';
```
Comment (ronjouch) [inline src/build/buildNativefierApp.ts:6]: If using a new third-party dep, you need to declare the extra dep in `package.json`

***BUT*** instead of that, I'd rather avoid the extra dependency (I strive to minimize the amount of third-party deps in Nativefier, to reduce bloat, security vulnerabilities, and upgrade hassle). You don't need an extra package to remove a directory, you can:

- A: use [fs.rmdir](https://nodejs.org/api/fs.html#fs_fs_rmdir_path_options_callback), which is callback-based, so to use it conveniently you'll have to write a little wrapper returning a promise (similar to what `fs-extra` does), like I did for `copyFileOrDir`:
https://github.com/jiahaog/nativefier/blob/f2c816795ac08c724809099ff01d71b022d5a1b4/src/helpers/helpers.ts#L39-L51
- B: simply use [fs.rmDirSync](https://nodejs.org/api/fs.html#fs_fs_rmdirsync_path_options)

Give A. a try, it isn't extra hard and I can help you if you haven't wrapped your head around promises.

File: src/build/buildNativefierApp.ts [hunk 2]
```diff
@@ -126,6 +128,14 @@ export async function buildNativefierApp(
   const appPath = getAppPath(appPathArray);
   await copyIconsIfNecessary(options, appPath);
 
+  if (options.nativefier.asar) {
+    console.log(`Creating asar file`);
```
Comment (ronjouch) [inline src/build/buildNativefierApp.ts:132]: Please use `log.info` instead of `console.log`

File: src/build/buildNativefierApp.ts [hunk 3]
```diff
@@ -1,7 +1,9 @@
 import * as path from 'path';
 
+import * as asar from 'asar';
```
Comment (ronjouch) [inline src/build/buildNativefierApp.ts:3]: Same as for `fs-extra`: if using a new third-party dep, you need to declare the extra dep in package.json.

But wait, all this is strange. Here you're doing `asar` packaging on your own, in Nativefier. We're not supposed to, Nativefier shouldn't have to re-implement it, it's already handled by electron-packager! https://electron.github.io/electron-packager/master/interfaces/electronpackager.options.html#asar . That's why right now in current Nativefier there basically zero code _do_ the packaging; normally we simply pass the `asar` option to electron-packager and it does the packaging for us.

Now, obviously, it's broken now, but rather than doing it here in Nativefier, I'd like to instead

1. Understand why it's broken now, maybe we're mis-using electron-packager or doing something it doesn't like
2. Reach out to electron-packager for help if necessary
3. If something's broken in electron-packager, offer a patch to them.

Please look at these.

**Review by ronjouch — CHANGES_REQUESTED** [review]

**Comment by ronjouch** [comment]
@sorhtyre see https://github.com/jiahaog/nativefier/pull/1074#discussion_r528444385 first and foremost.

File: src/build/buildNativefierApp.ts (hunk 3 above)
Comment (sorhtyre) [reply src/build/buildNativefierApp.ts:3]: The issue stems from the fact that `copyIconsIfNecessary()' occurs after `electronPackager()` completes.

As far as I can tell, there is no way to perform the copy action without the path generated from `electronPackager()`

**Comment by sorhtyre** [comment]
I think I did my homework this time and found that if the icon is copied to the tmp folder along with either pre-staged items (nativefier.jason..etc), it gets moved into the resources/app folder before electron-packager runs thus enabling the asar operation to run its course correctly.

**Review by ronjouch — COMMENTED** [review]
> I think I did my homework a little more thorough this time and found that if the icon is copied to the tmp folder along with other pre-staged items (nativefier.jason..etc), it gets moved into the resources/app folder before electron-packager runs thus enabling the asar operation to run its course correctly.
>
> This requires a much smaller change and doesn't include any new dependencies. In fact, it eliminates the need for one variable.

@sorhtyre yeah indeed, that makes a lot more sense, thanks for the second look 👍.

One last thing: your change fixes builds using our asar flag (`--conceal`). Do you confirm it doesn't break icons for ***normal (non-asar)*** builds?

**Comment by sorhtyre** [comment]
I was only able to test it on Linux, specifically Xubuntu 20.04. As far as I can tell, this will not break icon functionality on other OS's as it does not fundamentally change the handling of icons.

**Comment by ronjouch** [comment]
> I was only able to test it on Linux, specifically Xubuntu 20.04. As far as I can tell, this will not break icon functionality on other OS's as it does not fundamentally change the handling of icons.

@sorhtyre my question is not about OSes, it is about whether icons still work fine when *not* using the `--conceal` flag.

File: src/build/buildNativefierApp.ts [hunk 4]
```diff
@@ -65,9 +65,8 @@ async function copyIconsIfNecessary(
   }
 
   // windows & linux: put the icon file into the app
-  const destAppPath = path.join(appPath, 'resources/app');
   const destFileName = `icon${path.extname(options.packager.icon)}`;
-  const destIconPath = path.join(destAppPath, destFileName);
+  const destIconPath = path.join(appPath, destFileName);
```
Comment (ronjouch) [inline src/build/buildNativefierApp.ts:69]: Also: so now, icons would no longer live in `<path_to_app>/resources/app`, but instead in `<path_to_app>`. Was it necessary for your patch? I liked it in `<path_to_app>/resources/app`

Comment (sorhtyre) [reply src/build/buildNativefierApp.ts:69]: Icons will continue to live in `<path_to_app>/resources/app`.

The current patch copies icons to the pre-stage tmp folder, `appPath`. When electron-packager runs via `const appPathArray = await electronPackager(options.packager);` everything in the pre-stage folder gets moved into `<path_to_app>/resources/app`.

Rather than copy icons directly into `<path_to_app>/resources/app`, the patch allows electron-packager to handle the icon move thus enabling the asar function, while also preserving the `<path_to_app>/resources/app/icon.ext` scheme regardless of the `--conceal` option.

Comment (sorhtyre) [reply src/build/buildNativefierApp.ts:69]: without `--conceal`

image

Comment (sorhtyre) [reply src/build/buildNativefierApp.ts:69]: with `--concel`
image

Comment (sorhtyre) [reply src/build/buildNativefierApp.ts:69]: Sorry, I should have done a better job explaining it.

Comment (ronjouch) [reply src/build/buildNativefierApp.ts:69]: No worry, and thanks for the details/screenshots 👍

**Comment by ronjouch** [comment]
Merged. Thanks again @sorhtyre !
